### ISSUE TITLE
Updating / deprecating for docs built in fmralign ?

### ISSUE THREAD

**Issue by emdupre** [Parietal-INRIA/fmralign-docs#1]
Hi @bthirion !

I'd like to update the doc build (or deprecate this repo in favor of consolidating it into the fmralign repo), but I don't have permissions to edit.

Is there any chance you could add me here ? Would also love to know what you think re : where the build site should live. My preference would be to consolidate, given the relatively small size of the docs at present.

Thanks !

**Comment by bthirion** [comment]
Done. See you,
